In [3]:
import numpy as np

In [2]:
import array

In [5]:
# create array
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
type(np.array([1, 2, 3]))

numpy.ndarray

In [7]:
np.array([1, 2, 3 , 4, 5, "vithu", 5+8j,])

array(['1', '2', '3', '4', '5', 'vithu', '(5+8j)'], dtype='<U64')

In [8]:
np.array([1, 2, 3, 4.5, 6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [11]:
np.array([4, 2.0, "vithu", 5j])

array(['4', '2.0', 'vithu', '5j'], dtype='<U64')

In [18]:
np.array([[1, 2, 3], 
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [26]:
np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [24]:
type(np.array([[[1, 2, 3], [4, 5, 6]]]))

numpy.ndarray

In [27]:
np.array([1, 2, 3], ndmin = 3)

array([[[1, 2, 3]]])

In [28]:
np.array([1, 2, 3], ndmin = 30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [29]:
np.array([1, 2, 3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [34]:
np.array([1, 2, 3], dtype = str)

array(['1', '2', '3'], dtype='<U1')

In [35]:
np.array([1, 2, 3], dtype = float)

array([1., 2., 3.])

In [36]:
np.array([(1, 2), (4, 5)])

array([[1, 2],
       [4, 5]])

In [82]:
arr = np.array([(1, 2), (4, 5)], dtype = [("a", '<i4'), ("b", '<i8')])

In [83]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [84]:
type(arr[0][0])

numpy.int32

In [85]:
type(arr[0][1])

numpy.int64

In [87]:
arr = np.array([[1, 3], [3, 4]])

In [88]:
arr

array([[1, 3],
       [3, 4]])

In [91]:
arr[0]

array([1, 3])

In [92]:
arr[0][1]

3

In [95]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [96]:
np.matrix(arr)

matrix([[1, 3],
        [3, 4]])

In [97]:
l = [3, 4, 5, 6, 76, 7]

In [98]:
np.array(l)

array([ 3,  4,  5,  6, 76,  7])

In [100]:
np.asarray(l)

array([ 3,  4,  5,  6, 76,  7])

In [101]:
np.asanyarray(l)

array([ 3,  4,  5,  6, 76,  7])

In [102]:
mat = np.mat(arr)

In [104]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [105]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [106]:
issubclass(np.matrix, np.ndarray)

True

In [107]:
issubclass( np.ndarray, np.matrix)

False

In [108]:
arr

array([[1, 3],
       [3, 4]])

In [109]:
a = arr #shalloocopy

In [110]:
b = np.copy(arr) #deepcopy

In [111]:
arr[0][0] = 67

In [112]:
arr

array([[67,  3],
       [ 3,  4]])

In [113]:
a

array([[67,  3],
       [ 3,  4]])

In [114]:
b

array([[1, 3],
       [3, 4]])

In [116]:
arr[0:1]

array([[67,  3]])

In [117]:
arr[-1]

array([3, 4])

In [118]:
for i in arr:
    print (i)

[67  3]
[3 4]


In [119]:
np.fromfunction(lambda i, j : i == j, (4, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [120]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [122]:
np.fromfunction(lambda i, j : i/j, (3, 3))

C:\Users\Admin\AppData\Local\Temp\ipykernel_37116\1367875792.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i, j : i/j, (3, 3))
C:\Users\Admin\AppData\Local\Temp\ipykernel_37116\1367875792.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i, j : i/j, (3, 3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [121]:
1/0

ZeroDivisionError: division by zero

In [123]:
(i *i for i in range(5))

<generator object <genexpr> at 0x000001BD1403D2F0>

In [124]:
[i *i for i in range(5)]

[0, 1, 4, 9, 16]

In [125]:
def test(x):
    yield x

In [126]:
test(5)

<generator object test at 0x000001BD13F9DA80>

In [127]:
gen = (i *i for i in range(5))

In [128]:
gen

<generator object <genexpr> at 0x000001BD1403D490>

In [130]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [131]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [136]:
np.fromstring('1, 2, 3, 4, 5', sep = ',', dtype = int)

array([1, 2, 3, 4, 5])

In [139]:
np.fromstring("456 456 356 565 85", sep = " ")

array([456., 456., 356., 565.,  85.])

In [140]:
l = [3, 4, 5,6 ,7, 8]

In [142]:
arr = np.array(l)

In [148]:
arr1 = np.array([[1, 2, 3,4], [2 , 3, 4, 5], [4, 5, 6, 7]])

In [149]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [150]:
type(arr)

numpy.ndarray

In [153]:
arr1.ndim

2

In [154]:
arr1.size

12

In [155]:
arr1.shape

(3, 4)

In [156]:
arr1.dtype

dtype('int32')

In [157]:
arr

array([3, 4, 5, 6, 7, 8])

In [158]:
arr.size

6

In [159]:
arr.ndim

1

In [160]:
arr.shape

(6,)

In [166]:
arr2 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]]])

In [167]:
arr2

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [168]:
arr2.size

16

In [169]:
arr2.ndim

3

In [170]:
arr2.shape

(2, 2, 4)

In [172]:
list(range(5))

[0, 1, 2, 3, 4]

In [173]:
range(6.6) #it takes only whole number

TypeError: 'float' object cannot be interpreted as an integer

In [174]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [175]:
np.arange(6.6, 9, 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [176]:
np.arange(6.6, 9, -0.3)

array([], dtype=float64)

In [177]:
np.arange(9,6.6, -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [178]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [180]:
np.linspace(3, 8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [181]:
np.linspace(3, 5)

array([3.        , 3.04081633, 3.08163265, 3.12244898, 3.16326531,
       3.20408163, 3.24489796, 3.28571429, 3.32653061, 3.36734694,
       3.40816327, 3.44897959, 3.48979592, 3.53061224, 3.57142857,
       3.6122449 , 3.65306122, 3.69387755, 3.73469388, 3.7755102 ,
       3.81632653, 3.85714286, 3.89795918, 3.93877551, 3.97959184,
       4.02040816, 4.06122449, 4.10204082, 4.14285714, 4.18367347,
       4.2244898 , 4.26530612, 4.30612245, 4.34693878, 4.3877551 ,
       4.42857143, 4.46938776, 4.51020408, 4.55102041, 4.59183673,
       4.63265306, 4.67346939, 4.71428571, 4.75510204, 4.79591837,
       4.83673469, 4.87755102, 4.91836735, 4.95918367, 5.        ])

In [182]:
np.linspace(3, 5, 3)

array([3., 4., 5.])

In [187]:
np.linspace(1, 15, 10)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [189]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [192]:
np.zeros((2, 5, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [193]:
np.ones(4)

array([1., 1., 1., 1.])

In [194]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [197]:
np.ones((5, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [199]:
np.ones((5, 3, 2)) + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [201]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [202]:
np.empty((3, 4))

array([[1.01855798e-312, 1.10343781e-312, 1.03977794e-312,
        9.54898106e-313],
       [1.10343781e-312, 1.01855798e-312, 1.23075756e-312,
        1.12465777e-312],
       [1.10343781e-312, 9.76118064e-313, 1.10343781e-312,
        1.90979621e-312]])

In [204]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [205]:
np.linspace(2, 4, 4, endpoint = False)

array([2. , 2.5, 3. , 3.5])

In [209]:
np.linspace(2, 4, 4, endpoint = False, axis = 0)

array([2. , 2.5, 3. , 3.5])

In [210]:
np.logspace(2, 3, 5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])