# Chi- Square Test - 2024.06.01

- The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables.

In [1]:
import scipy.stats as stats

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
dataset = sns.load_dataset("tips")

In [6]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
dataset_table = pd.crosstab(dataset["sex"], dataset["smoker"])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [11]:
observed_values = dataset_table.values
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [12]:
val = stats.chi2_contingency(dataset_table)
val

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

In [13]:
val[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
expected_Values = val[3]
expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [15]:
no_of_rows = len(dataset_table.iloc[0:2, 0])
no_of_columns = len(dataset_table.iloc[0, 0:2])
ddof = (no_of_rows - 1) * (no_of_columns - 1)
print("Degree of Freedom : ", ddof)
alpha = 0.05

Degree of Freedom :  1


In [16]:
from scipy.stats import chi2

In [17]:
chi_square = sum([(o - e) ** 2. / e for o, e in zip(observed_values, expected_Values)])
chi_square_statistic = chi_square[0] + chi_square[1]

In [18]:
print("Chi-Square Statistic : ", chi_square_statistic)

Chi-Square Statistic :  0.001934818536627623


In [19]:
critical_value = chi2.ppf(q = 1 - alpha, df = ddof)
print("Crifical Value : ", critical_value)

Crifical Value :  3.841458820694124


In [20]:
#p value
p_value = 1 - chi2.cdf(x = chi_square_statistic, df = ddof)
print("p-value : ", p_value)
print("Significan Level : ", alpha)
print("Degree of Freedom : ", ddof)

p-value :  0.964915107315732
Significan Level :  0.05
Degree of Freedom :  1


In [22]:
if chi_square_statistic >= critical_value:
    print("Reject H0, There is a relatonship between 2 caegorical variables")
else:
    print("Retain H0, There is no relatonship between 2 caegorical variables")

Retain H0, There is no relatonship between 2 caegorical variables


In [23]:
if p_value <= alpha:
    print("Reject H0, There is a relatonship between 2 caegorical variables")
else:
    print("Retain H0, There is no relatonship between 2 caegorical variables")

Retain H0, There is no relatonship between 2 caegorical variables
